# Name of application
spring.application.name=SnofjallbyWithPT-Backend

# Set up logging level in Spring Boot
logging.level.org.springframework.security=DEBUG

# Ensures that every new user created is unique
spring.data.mongodb.auto-index-creation=true

# SnofjallbyWithPT-Backend MongoDB - PRIMARY Server config - SECONDARY locally
###############################################
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/snofjallby}

################## RabbitMq config ##################
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}