# Name of application
spring.application.name=flakeville-server

# Log-level for security
logging.level.org.springframework.security=DEBUG
# Ensures that every new user created is unique in mongodb database
spring.data.mongodb.auto-index-creation=true



## Common Server+Local env.variable config == {Server PRIMARY:SECONDARY locally} ##
## MONGODB_URI and ADMIN_PASSWORD in OS env. variables ##

################## MongoDB ##################
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/flakeville}
################## RabbitMq ##################
spring.rabbitmq.host=${RABBITMESSAGEQUEUE_HOST:localhost}
spring.rabbitmq.port=${RABBITMESSAGEQUEUE_PORT:5672}
spring.rabbitmq.username=${RABBITMESSAGEQUEUE_USERNAME:guest}
spring.rabbitmq.password=${RABBITMESSAGEQUEUE_PASSWORD:guest}