# Name of application
spring.application.name=flakeville-server

# Set up logging level in Spring Boot
logging.level.org.springframework.security=DEBUG

# Ensures that every new user created is unique in mongodb database
spring.data.mongodb.auto-index-creation=true

# flakeville database MongoDB {Server PRIMARY:SECONDARY locally}
###############################################
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/flakeville}

################## RabbitMq config ##################
spring.rabbitmq.host=${RABBITMESSAGEQUEUE_HOST}
spring.rabbitmq.port=${RABBITMESSAGEQUEUE_PORT}
spring.rabbitmq.username=${RABBITMESSAGEQUEUE_USERNAME}
spring.rabbitmq.password=${RABBITMESSAGEQUEUE_PASSWORD}