name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Print MONGODB_URI
        run: echo ${{ secrets.MONGODB_URI }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run tests
        run: mvn test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}